# Generated by Django 4.0.6 on 2022-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_followrs_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrs',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
