# Generated by Django 4.0.6 on 2022-07-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_followrs_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrs',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
