# Generated by Django 4.0.6 on 2022-07-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_followrs_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followrs',
            name='number',
        ),
    ]
